### ISSUE TITLE
Uncaught TypeError: (0 , react_virtual_1.useVirtualizer) is not a function

### ISSUE THREAD

**Issue by TigerDev007** [nick-keller/react-datasheet-grid#337]
After installing package, I have got the error like this. I used the typescript.

![Screenshot_13](https://github.com/nick-keller/react-datasheet-grid/assets/161411308/e37f88ab-83bb-449b-b1d4-6940fe0cd5cf)

**Comment by Harsha1401** [comment]
we are also getting same error , this is because of auto upgrade of @tanstack/react-virtual  to 3.1.3... it is working we use  
 like below in package.json@tanstack/react-virtual : 3.0.4 as ` "resolutions": {  
    "@tanstack/react-virtual": "3.0.4"
  }`

Grid.js:74 Uncaught TypeError: (0 , react_virtual_1.useVirtualizer) is not a function
at Grid (Grid.js:74:1)
at renderWithHooks (react-dom.development.js:12974:1)
at mountIndeterminateComponent (react-dom.development.js:15457:1)
at beginWork (react-dom.development.js:16510:1)
at HTMLUnknownElement.callCallback (react-dom.development.js:3551:1)
at Object.invokeGuardedCallbackDev (react-dom.development.js:3595:1)
at invokeGuardedCallback (react-dom.development.js:3650:1)
at beginWork$1 (react-dom.development.js:20646:1)
at performUnitOfWork (react-dom.development.js:19657:1)
at workLoopSync (react-dom.development.js:19602:1)

**Comment by taylorraywilson** [comment]
> we are also getting same error , this is because of auto upgrade of @tanstack/react-virtual to 3.1.3... it is working we use like below in package.json@tanstack/react-virtual : 3.0.4 as ` "resolutions": { "@tanstack/react-virtual": "3.0.4" }`

For **npm** users, it is not _resolutions_, it is [overrides](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#overrides). Yarn is resolutions.

**Comment by DIPANKAR-123** [comment]
Thanks you so much @taylorraywilson .
